# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 809bc98c9278b683a8ee0ebabaac67df77841117667c61f1e8d166e71b6cd05a3a37ef56afb15f27874e429889889f77ccfcccdc7c508aa60726ab548a1552b5

test:
  secret_key_base: fa1dbd0f1cdf6d07c07ca5e22432cf5a108df08196a888f6288d2a1c083858f21d07e35253a16ad3c5ec321d458024d880e61b1e7874c3d3aa9153acd5f14651

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
